name: CI

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
  release:
    types:
      - created

jobs:

  # This job will:
  #   * deploy a draft every time there is a pull request created or synchronized that is not on master branch
  #   * comment on that pull request with the deploy URL
  deployPRDraft:
    name: Deploy draft to Netlify on Pull Request
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      # Build steps for gatsby build
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          
      # check pwd
      - run: pwd
        working-directory: dev
        # Install all dependencies
      - run: npm install
        working-directory: dev
      
      # This triggers `react build` script in "package.json"
      - run: npm run build
        working-directory: dev
        env:
         CI: false

      - name: Deploy draft to Netlify on PR
        uses: South-Paw/action-netlify-deploy@v1.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './dev/build'
          draft: true
          comment-on-pull-request: true
    
  # This job will:
  #   * deploy a draft every time there is a commit that is not on master branch
  #   * comment on that commit with the deploy URL
  deployCommitDraft:
    name: Deploy draft to Netlify on Commit
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref != 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      # Build steps for gatsby build
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

            # check pwd
      - run: pwd
        working-directory: dev
        # Install all dependencies
      - run: npm install
        working-directory: dev
      
      # This triggers `react build` script in "package.json"
      - run: npm run build
        working-directory: dev
        env:
         CI: false

      - name: Deploy draft to Netlify on push
        uses: South-Paw/action-netlify-deploy@v1.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './dev/build'
          draft: true
          comment-on-commit: true


  # This job will:
  #   * deploy a production build every time there is a release created on the master branch
  #   * comment that commit with the deploy URL
  publishOnMasterRelease:
    name: Publish release to Netlify
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      # Build steps for gatsby build
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          
          # check pwd
      - run: pwd
        working-directory: dev
        # Install all dependencies
      - run: npm install
        working-directory: dev
      
      # This triggers `react build` script in "package.json"
      - run: npm run build
        working-directory: dev
        env:
         CI: false

      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './dev/build'
          
